In [2]:
import numpy as np
#Azhara Devi Sandi
#A11.2018.11392
#UAS- KECERDASAN BUATAN
#Menggunakan algortitma genetika

jumlah_populasi=6
jumlah_gen=4

#Pembentukan & Inisialiasasi chromosome
chromosome=np.random.randint(0,30,(jumlah_populasi,jumlah_gen))
print("------Tahap Pembentukan dan Inisialisasi Chromosome------")
print(chromosome)
print("---------------------------------------------------------")
print()

epoch=0

while epoch < 50:
    print()
    print("GENERASI ",epoch+1," =")
    
    #EVALUASI
    print("------Tahap Evaluasi------")
    #perhitungan fungsi objektif atau fo
    fo=abs((chromosome[:,0]+2*chromosome[:,1]+3*chromosome[:,2]+4*chromosome[:,3])-30)
    print("Fungsi Objektif =", fo)
    
    #rata-rata fungsi objektif
    total_fo=fo.sum()
    rata_fo=total_fo/jumlah_populasi
    print("Rata - rata fungsi objektif =", rata_fo)
    
    print("---------------------------------------------------------")
    print()
    
    #SELEKSI CHROMOSOME
    print("------Tahap Seleksi------")
    #perhitungan fitness atau fit
    fit=1/(1+fo)
    print("Fitness =", fit)
    
    #total fitness
    total_fit=fit.sum()
    
    #mencari nilai probabilitas
    prob=fit/total_fit
    print("Probabilitas =", prob)
    
    #nilai kumulatif
    C=np.cumsum(prob)
    print("Nilai cumulative =", C)
    
    #seleksi menggunakan roulete wheel
    #range angka 0-1
    R=np.random.random((chromosome.shape[0]))
    print("Roulette Wheel =", R)
    
    #proses pembuatan chromosome baru yang telah diseleksi
    new_chrom=np.zeros((chromosome.shape[0], jumlah_gen))
    
    for x in range(R.shape[0]):
        for k in range(chromosome.shape[0]):
            if R[x]<C[0]:
                new_chrom[x]=chromosome[0]
            elif (C[k-1]<R[x]) & (R[x]<C[k]):
                new_chrom[x]=chromosome[k]
    chromosome=new_chrom
    print("Chromosome baru hasil proses seleksi =")
    print(chromosome)
    
    print("---------------------------------------------------------")
    print()
    
    #CROSSOVER
    print("------Tahap Crossover------")
    #mencari bilangan acak R
    R_cross=[np.random.random() for x in range(jumlah_populasi)]
    print("Nilai random crossover =", R_cross)
    
    #crossover probability 25%
    pc=0.25
    flag=R<pc
    print("Flagged Values =", flag)
    
    #menentukan posisi dari crossover
    #jika R<pc maka = TRUE
    cross_chromosome=chromosome[[(x==True) for x in flag]]
    print("Posisi Crossover =", cross_chromosome)
    panjang_cross=len(cross_chromosome)
    
    #mencari cross values
    cross_values=np.random.randint(1,3,panjang_cross)
    print("Cross values =", cross_values)
    
    #proses menjalankan crossover
    copy_chrom=np.zeros(cross_chromosome.shape)
    for x in range(cross_chromosome.shape[0]):
        copy_chrom[x,:]=chromosome[x,:]
    if panjang_cross == 1:
        cross_chrom = cross_chromosome
    else :
        for x in range(panjang_cross):
            c_val = cross_values[x]
            if x == panjang_cross - 1 :
                cross_chromosome[x , c_val:] = copy_chrom[0 , c_val:]
            else :
                cross_chromosome[x , c_val:] = copy_chrom[x+1 , c_val:]
    print("Hasil offspring :", cross_chromosome)
    
    index_chromosome=0
    index_newchrom=0
    for x in flag:
        if x==True:
            chromosome[index_chromosome,:]=cross_chromosome[index_newchrom,:]
            index_newchrom=index_newchrom+1
        index_chromosome=index_chromosome+1
    print("Chromosome baru hasil Crossover =")
    print(chromosome)
    
    print("---------------------------------------------------------")
    print()
    
    #MUTASI
    print("------Tahap Mutasi------")
    #menghitung total gen
    a,b=chromosome.shape[0],chromosome.shape[1]
    total_gen=a*b
    print("Total gen =", total_gen)
    
    #mencari jumlah mutasi rate 10%
    pm=0.1
    jumlah_mutasi=int(np.round(pm*total_gen))
#     jumlah_mutasi=pm*total_gen
    print("Jumlah Mutasi =", jumlah_mutasi)
     
    #mencari nilai gen chromosome yang akan dimutasi secara acak
    gen_num=np.random.randint(0,total_gen-1,jumlah_mutasi)
    print("Bilangan gen yang akan dimutasi =", gen_num)
    
    #mencari bil acak untuk mengganti gen_num
    ganti_num=np.random.randint(0,30,jumlah_mutasi)
    print("Bilangan acak yang terbangkitkan =", ganti_num)
    
    #memasukan ganti_num kedalam chromosome
    for x in range(jumlah_mutasi):
        a=gen_num[x]
        row=a//4
        col=a%4
        chromosome[row,col]=ganti_num[x]
    print("Chromosome baru hasil Mutasi =")
    print(chromosome)
    
    #cetak chromosome terbaik
    print("---------------------------------------------------------")
    print()
    print("Chromosome terbaik =", chromosome[jumlah_gen])
    
    epoch=epoch+1    


------Tahap Pembentukan dan Inisialisasi Chromosome------
[[ 2  2  7  3]
 [18  3 23  3]
 [ 9 15 10 18]
 [21  8 13 19]
 [20 11 18 18]
 [11  8  9  6]]
---------------------------------------------------------


GENERASI  1  =
------Tahap Evaluasi------
Fungsi Objektif = [  9  75 111 122 138  48]
Rata - rata fungsi objektif = 83.83333333333333
---------------------------------------------------------

------Tahap Seleksi------
Fitness = [0.1        0.01315789 0.00892857 0.00813008 0.00719424 0.02040816]
Probabilitas = [0.63363745 0.08337335 0.05657477 0.05151524 0.04558543 0.12931376]
Nilai cumulative = [0.63363745 0.7170108  0.77358557 0.82510081 0.87068624 1.        ]
Roulette Wheel = [0.09160288 0.90950424 0.71370396 0.79537383 0.44413905 0.4892665 ]
Chromosome baru hasil proses seleksi =
[[ 2.  2.  7.  3.]
 [11.  8.  9.  6.]
 [18.  3. 23.  3.]
 [21.  8. 13. 19.]
 [ 2.  2.  7.  3.]
 [ 2.  2.  7.  3.]]
---------------------------------------------------------

------Tahap Crossover-----